
 
spring:
  datasource:
    url: jdbc:h2:mem:taxdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  h2:
    console:
      enabled: true     
      
eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.99.100:8090/eureka
    instance:
      appname: ${spring.application.name}-${random.int}

msg: Hello world - this is from config server prod environment